version: 2

project_name: helm-resource

builds:
  - id: default
    main: .
    binary: bin/resource
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/m-pavel/helm-resource/cmd.Version={{ .Version }}

archives:
  - format: tgz
    name_template: '{{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}'
    wrap_in_directory: resource

changelog:
  use: github-native

release:
